#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html><head><title>System Status</title>"
echo "<style>"
echo "body { font-family: monospace; background: #1a1a2e; color: #0f0; padding: 40px; }"
echo "h1 { color: #00d4ff; }"
echo ".status { background: #000; padding: 20px; border-radius: 10px; margin-top: 20px; }"
echo "a { color: #00d4ff; }"
echo "</style></head><body>"
echo "<h1>System Status</h1>"
echo "<div class='status'>"
echo "<p><strong>Server:</strong> $(uname -n)</p>"
echo "<p><strong>OS:</strong> $(uname -s) $(uname -r)</p>"
echo "<p><strong>Uptime:</strong> $(uptime -p 2>/dev/null || uptime)</p>"
echo "<p><strong>Date:</strong> $(date)</p>"
echo "<p><strong>Apache Version:</strong> $(/usr/local/apache2/bin/httpd -v 2>&1 | head -1)</p>"
echo "</div>"
echo "<p style='margin-top: 20px;'><a href='/'>Back to Home</a></p>"
echo "</body></html>"
